kind: Deployment
metadata:
  name: medicure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
      - name: medicure
        image: 025066243934.dkr.ecr.us-west-1.amazonaws.com/noni:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: medicure-service
  type: NodePort  
  ports:
  - port: 8082           # The port that will be exposed externally
    targetPort: 8082      # The port the container is listening on
  selector:
    app: medicure  # This ensures the service connects to the app pods
